const data = {
    result: {
        status_ok: 1,
        curPage: 1,
        scriptList: [
            {
                file_path: "/scripts/1/391E98C0C4DB48AB80202C05E515F9CA",
                notes: "자동화 테스트 스크립트 설명-4325",
                job_label: "시스템1-업무10",
                file_size2: "137 Kb",
                system_id: 1,
                num: 1,
                type: 2,
                file_size: 140150,
                statusLabel: "초안",
                last_author_name: "관리자",
                notes2: "자동화 테스트 스크립트 설명-4325",
                job_id: 10,
                creation_dt: "2021-02-19 14:05:42",
                authorName: "장신한",
                name: "homepage_conn.xml",
                id: 4325,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 12206,
                status: "D",
                last_edit_date: "2022-04-04 18:14:27",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4324",
                job_label: "시스템1-업무6",
                file_size2: "115 Kb",
                system_id: 1,
                num: 2,
                type: 2,
                file_size: 118119,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4324",
                job_id: 6,
                creation_dt: "2021-02-18 17:19:46",
                authorName: "유신한",
                name: "자동화 테스트 스크립트 파일-4324",
                id: 4324,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 15316,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4323",
                job_label: "시스템1-업무14",
                file_size2: "26 Kb",
                system_id: 1,
                num: 3,
                type: 2,
                file_size: 26562,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4323",
                job_id: 14,
                creation_dt: "2021-02-17 17:02:23",
                authorName: "김신한",
                name: "자동화 테스트 스크립트 파일-4323",
                id: 4323,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 12584,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4322",
                job_label: "시스템1-업무14",
                file_size2: "25 Kb",
                system_id: 1,
                num: 4,
                type: 2,
                file_size: 25106,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4322",
                job_id: 14,
                creation_dt: "2021-02-17 17:01:56",
                authorName: "김신한",
                name: "자동화 테스트 스크립트 파일-4322",
                id: 4322,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 12584,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4321",
                job_label: "시스템1-업무17",
                file_size2: "274 Kb",
                system_id: 1,
                num: 5,
                type: 2,
                file_size: 281075,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4321",
                job_id: 17,
                creation_dt: "2021-02-16 15:56:48",
                authorName: "김신한",
                name: "자동화 테스트 스크립트 파일-4321",
                id: 4321,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 11517,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4320",
                job_label: "시스템1-업무14",
                file_size2: "27 Kb",
                system_id: 1,
                num: 6,
                type: 2,
                file_size: 27183,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4320",
                job_id: 14,
                creation_dt: "2021-02-16 15:15:01",
                authorName: "이신한",
                name: "자동화 테스트 스크립트 파일-4320",
                id: 4320,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 14016,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4319",
                job_label: "시스템1-업무14",
                file_size2: "96 Kb",
                system_id: 1,
                num: 7,
                type: 2,
                file_size: 98440,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4319",
                job_id: 14,
                creation_dt: "2021-02-16 14:54:16",
                authorName: "안신한",
                name: "자동화 테스트 스크립트 파일-4319",
                id: 4319,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 15475,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/scripts/1/0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4318",
                job_label: "시스템1-업무13",
                file_size2: "62 Kb",
                system_id: 1,
                num: 8,
                type: 2,
                file_size: 63367,
                statusLabel: "초안",
                last_author_name: "전신한",
                notes2: "자동화 테스트 스크립트 설명-4318",
                job_id: 13,
                creation_dt: "2021-02-16 13:14:33",
                authorName: "전신한",
                name: "자동화 테스트 스크립트 파일-4318",
                id: 4318,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 10189,
                status: "D",
                last_edit_date: "2021-02-16 13:29:42",
            },
            {
                file_path: "/scripts/1/0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4317",
                job_label: "시스템1-업무14",
                file_size2: "40 Kb",
                system_id: 1,
                num: 9,
                type: 2,
                file_size: 41049,
                statusLabel: "초안",
                last_author_name: "이신한",
                notes2: "자동화 테스트 스크립트 설명-4317",
                job_id: 14,
                creation_dt: "2021-02-15 15:55:58",
                authorName: "이신한",
                name: "자동화 테스트 스크립트 파일-4317",
                id: 4317,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 14016,
                status: "D",
                last_edit_date: "2021-02-15 15:59:27",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4316",
                job_label: "시스템1-업무1",
                file_size2: "98 Kb",
                system_id: 1,
                num: 10,
                type: 2,
                file_size: 100219,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4316",
                job_id: 1,
                creation_dt: "2021-02-15 15:38:55",
                authorName: "안신한",
                name: "자동화 테스트 스크립트 파일-4316",
                id: 4316,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 15475,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4315",
                job_label: "시스템1-업무1",
                file_size2: "129 Kb",
                system_id: 1,
                num: 11,
                type: 2,
                file_size: 131596,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4315",
                job_id: 1,
                creation_dt: "2021-02-15 11:05:22",
                authorName: "김신한",
                name: "자동화 테스트 스크립트 파일-4315",
                id: 4315,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 11517,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4314",
                job_label: "시스템1-업무14",
                file_size2: "118 Kb",
                system_id: 1,
                num: 12,
                type: 2,
                file_size: 121298,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4314",
                job_id: 14,
                creation_dt: "2021-02-15 10:32:19",
                authorName: "안신한",
                name: "자동화 테스트 스크립트 파일-4314",
                id: 4314,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 15475,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4313",
                job_label: "시스템1-업무16",
                file_size2: "65 Kb",
                system_id: 1,
                num: 13,
                type: 2,
                file_size: 66138,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4313",
                job_id: 16,
                creation_dt: "2021-02-10 14:33:16",
                authorName: "김신한",
                name: "자동화 테스트 스크립트 파일-4313",
                id: 4313,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 11517,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4311",
                job_label: "시스템1-업무14",
                file_size2: "125 Kb",
                system_id: 1,
                num: 14,
                type: 2,
                file_size: 128197,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4311",
                job_id: 14,
                creation_dt: "2021-02-09 15:27:43",
                authorName: "안신한",
                name: "자동화 테스트 스크립트 파일-4311",
                id: 4311,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 15475,
                status: "D",
                last_edit_date: "",
            },
            {
                file_path: "/1/scripts//0A1B2C3D4E5F6G7H8I9J0A1B2C3D4E5F",
                notes: "자동화 테스트 스크립트 설명-4310",
                job_label: "시스템1-업무14",
                file_size2: "31 Kb",
                system_id: 1,
                num: 15,
                type: 2,
                file_size: 32146,
                statusLabel: "초안",
                last_author_name: "",
                notes2: "자동화 테스트 스크립트 설명-4310",
                job_id: 14,
                creation_dt: "2021-02-09 14:33:47",
                authorName: "김신한",
                name: "자동화 테스트 스크립트 파일-4310",
                id: 4310,
                type_label: "Desktop",
                system_label: "시스템-1",
                author_id: 12584,
                status: "D",
                last_edit_date: "",
            },
        ],
        paging: {
            blockSize: 5,
            prevPage: 1,
            nextPage: 6,
            totalPageCount: 266,
            totalBlockCount: 53,
            curBlock: 1,
            prevBlock: 0,
            nextBlock: 0,
            startBlock: 1,
            endBlock: 5,
        },
        totalCount: 3982,
    },
};

export const config = {
    title: "스크립트 목록",
    source: data.result.scriptList,
    target: {
        num: "번호",
        system_label: "시스템",
        job_label: "업무",
        name: "파일명",
        notes: "설명",
        type_label: "종류",
        file_size2: "크기",
        authorName: "등록자",
        creation_dt: "등록일",
    },
    // templateUrl: "/up_/assets/template.xlsx",
};
